openapi: 3.0.0
info:
  title: Gusto API
  version: '1.0'
  termsOfService: 'https://gusto.com/about/terms'
  contact:
    name: Developer Relations
    email: developer@gusto.com
servers:
  - url: 'https://api.gusto-demo.com'
    description: Demo
  - description: Production
    url: 'https://api.gusto-demo.com'
paths: {}
components:
  schemas: {}
  securitySchemes: {}
