swagger: '2.0'
info:
  title: Gusto API Documentation
  version: '1.0'
  description: Gusto API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

host: 'api.gusto.com'
schemes:
  - https
basePath: /v1
x-tagGroups:
  - name: Introduction
    tags:
      - Authentication
      - Versioning
      - Syncing Employees
  - name: Examples
    tags:
      - Updating Payrolls
  - name: API Reference
    tags:
      - Companies
      - Employees
      - Jobs

tags:
  - name: Authentication
    x-traitTag: true
    description: >-
      Authentication info goes here
  - name: Versioning
    x-traitTag: true
    description: >-
      Versioning blurb here
  - name: Syncing Employees
    x-traitTag: true
    description: >-
      stuff here
  - name: Updating Payrolls
    x-traitTag: true
    description: >-
      updating payroll example

paths:

  /companies/{company_id}/employees:
    $ref: 'employees/list.yaml'

  /employees/{employee_id}:
    $ref: 'employees/detail.yaml'

  /employees/{employee_id}/jobs:
    $ref: 'jobs/list.yaml'

  /jobs/{job_id}:
    $ref: 'jobs/detail.yaml'
