swagger: '2.0'
info:
  title: Gusto API Documentation
  version: '1.0'
  description: Gusto API
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

host: 'api.gusto.com'
schemes:
  - https
basePath: /v1
x-tagGroups:
  - name: Introduction
    tags:
      - Authentication
      - Versioning
      - Syncing Employees
  - name: Examples
    tags:
      - Updating Payrolls

tags:
  - name: Authentication
    x-traitTag: true
    description: >-
      Authentication info goes here
  - name: Versioning
    x-traitTag: true
    description: >-
      Versioning blurb here
  - name: Syncing Employees
    x-traitTag: true
    description: >-
      stuff here
  - name: Updating Payrolls
    x-traitTag: true
    description: >-
      updating payroll example
      
paths:
  /:
    get:
      summary: base
      description: >-
        Gusto API
      responses:
        '200':
          description: OK
      tags:
        - Base
      operationId: base_read
