name: Spectral Linting Check
on: pull_request
jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@v0.8.1
        with:
          file_glob: reference/*.yaml
